name: "Invite User to Slack on Access Approval"
on:
  issues:
    types: [labeled]

jobs:
  invite-to-slack:
    if: github.event.label.name == 'access-approved'
    runs-on: ubuntu-latest
    steps:
      - name: Extract email and invite to Slack
        uses: actions/github-script@v7
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          script: |
            const emailRegex = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/;
            const issueBody = context.payload.issue.body || "";
            const match = issueBody.match(emailRegex);
            if (!match) {
              core.setFailed("No e-mail address found in the issue body.");
              return;
            }
            const email = match[0];
            // Optionally, add more email validation here if desired

            // Call Slack API to invite user
            const fetch = require('node-fetch');
            const SLACK_TEAM_ID = 'T08TKC56VQ8';

            const res = await fetch('https://slack.com/api/admin.users.invite', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${process.env.SLACK_BOT_TOKEN}`,
                'Content-Type': 'application/json; charset=utf-8',
              },
              body: JSON.stringify({
                channel_ids: C08TKC5G140
                email: email,
                team_id: SLACK_TEAM_ID
              }),
            });

            const result = await res.json();
            if (!result.ok) {
              core.setFailed(`Slack API error: ${result.error}`);
            } else {
              core.info(`Invited ${email} to Slack.`);
            }
